#!/bin/bash

group=$(egrep "^[^:]+:[^:]+:${SVN_GID:-0}:" /etc/group | cut -d: -f 1)
if [ -z "$group" ] ; then
    # Group with gid does not exist
    group="svnserve"
    addgroup --gid "$SVN_GID" "$group"
fi

user=$(egrep "^[^:]+:[^:]+:${SVN_UID:-0}:" /etc/passwd | cut -d: -f 1)
if [ -n "$user" ] ; then
    # User with the uid already exists
    # Set the primary group for the existing user
    usermod -g "$group" "$user"
else
    # User with the uid does not exist and should be added
    user="svnserve"
    adduser --home "/svn" --no-create-home --gecos "" \
        --uid "${SVN_UID:-0}" --gid "${SVN_GID:-0}" \
        --disabled-password "$user"
fi

optional_args=
if [ -n "$SVN_LOG" ] ; then
    optional_args="--log-file $SVN_LOG"
fi

# Generate xinetd configuration
cat > /etc/xinetd.d/svnserve <<END
service svn
{
    disable = no
    socket_type = stream
    protocol = tcp
    wait = no
    log_type = FILE ${CONNECTION_LOG:-/var/log/svnserve_connection.log}
    instances = UNLIMITED
    cps = 100 10
    log_on_success = HOST PID EXIT DURATION
    log_on_failure = HOST
    user = $user
    group = $group
    server = /usr/bin/svnserve
    server_args = --inetd --root /svn $optional_args
}
END

exec /usr/sbin/xinetd -dontfork
